"""adding active on Member

Revision ID: c9083f2f781b
Revises: e5e2106a8e99
Create Date: 2025-08-20 08:53:36.284361

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c9083f2f781b'
down_revision: str | Sequence[str] | None = 'e5e2106a8e99'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'active')
    # ### end Alembic commands ###
